python train.py --data_dir E:/Projects/CRL/Flood_CRL_demo/labelled_samples/labelled_samples/ \
                --dataloader_workers 4 \
                --annotation_path E:/Projects/CRL/Flood_CRL_demo/labelled_samples/annotations.csv \
                --sampling_size 256 \
                --labels flood \
                --dec_dist implicit \
                --d_steps_per_iter 1 \
                --sample_every_epoch 5 \
                --latent_dim 100 \
                --enc_arch resnet \
                --save_model_every 5 \
                --n_epochs 200 \
                --prior linscm \
                --sup_prop 1 \
                --sup_coef 5 \
                --sup_type ce \
                --dataset flood